// pubspec.yaml の version フィールドから lib/src/version.g.dart を生成する。
// 実行: dart run tool/generate_version.dart
import 'dart:io';

import 'package:yaml/yaml.dart';

void main() {
  final pubspecFile = File('pubspec.yaml');
  final pubspec = loadYaml(pubspecFile.readAsStringSync()) as Map;
  final version = pubspec['version'] as String;

  final buffer = StringBuffer()
    ..writeln('// GENERATED FILE — DO NOT EDIT.')
    ..writeln('// Generated by tool/generate_version.dart from pubspec.yaml.')
    ..writeln()
    ..writeln("const String packageVersion = '$version';");

  final outFile = File('lib/src/version.g.dart');
  outFile.writeAsStringSync(buffer.toString());
  stdout.writeln('Wrote ${outFile.path} (version: $version)');
}
