/// `utakata.lock` — knowledge_repo フェッチ結果のコミット SHA 固定(実装計画 D3)。
///
/// `utakata arch get --update` を明示実行するまで SHA は変わらない。
/// サプライチェーン注入・再現性喪失への最小対策。
final class KnowledgeLock {
  final String url;
  final String ref;
  final String sha;
  final String fetchedAt;

  const KnowledgeLock({
    required this.url,
    required this.ref,
    required this.sha,
    required this.fetchedAt,
  });

  factory KnowledgeLock.fromMap(Map<String, dynamic> map) {
    final repo = map['knowledge_repo'];
    if (repo is! Map) {
      throw const FormatException('utakata.lock: knowledge_repo section missing');
    }
    return KnowledgeLock(
      url: repo['url'] as String,
      ref: (repo['ref'] ?? '') as String,
      sha: repo['sha'] as String,
      fetchedAt: (repo['fetched_at'] ?? '') as String,
    );
  }

  String toYaml() => '''
# GENERATED by `utakata arch get` — DO NOT EDIT.
knowledge_repo:
  url: "$url"
  ref: "$ref"
  sha: "$sha"
  fetched_at: "$fetchedAt"
''';
}
